import { createSlice } from '@reduxjs/toolkit';
import { COMMENTS } from '../../app/shared/COMMENTS';

// Define the initial state with comments data
const initialState = {
    commentsArray: COMMENTS
};

// Create a Redux slice for managing comments
const commentSlice = createSlice({
    name: 'comments',
    initialState
});

// Export the reducer generated by createSlice
export const commentsReducer = commentSlice.reducer;

// Define a selector function to select comments by campsiteId
export const selectCommentsByCampsiteId = (campsiteId) => (state) => {
    return state.comments.commentsArray.filter(
        (comment) => comment.campsiteId === parseInt(campsiteId)
    );
};